### PR TITLE
[WIP] Patches for cross compiling rust's libcore.

### PR DESCRIPTION
**Pull request by dvc94ch**
Missing features to compile rust's libcore for RV32IMA:
- [x] bswap intrinsic
- [ ] return arguments through stack
- [x] Stack adjustment outside of 12-bit imm range
- [x] M extension
- [ ] A extension
- [x] Privileged instructions
- [x] insertBranch (required for optimizations)
- [x] lld: Implement relocations emitted by llvm

### CODE REVIEW

**Comment by asb** [comment]
Hi David, this is looking very interesting so far. Many, many thanks for the contribution. My plan is that in the not too distant future, enough of the RISC-V LLVM backend will be upstreamed in LLVM, meaning most development can occur directly there. It would hope to use issues on this repository to co-ordinate development, and maintain the patches primarily as a useful artefact for people wanting to see how to incrementally build a backend. I just wanted to explain why it's a bit awkward to collaborate on patches in this repository, and the plan for fixing it.

I had a slightly different take on supporting larger stacks - let me clean that patch up and compare.

I believe that your support for ret i128 isn't ABI-compliant. Return values of greater than 2x xlen should be returned via reference (the frontend should have modified the function prototype to take a new parameter holding a pointer to the memory where the return value should be written). If this was motivated by assertion errors due to libcalls being inserted during legalization, the fix is slightly more complex. There is currently a `markLibCallAttributes` function which can be used to fix-up a similar ABI issue for the x86 MCU ABI. I haven't yet done this, but it looks promising to introduce a `libcallABILowering` function that replaces this. It can add appropriate attributes for x86 MCU, and hopefully modify the parameters to pass a pointer to the return value on RISCV.

Thanks again. I'm looking forward to collaborating with you on the RISC-V LLVM backend.

**Comment by dvc94ch** [comment]
I copied some other archs c-abi code in rustc, I guess that's the problem... It was my understanding that that code was only relevant for interfacing with other c code because rust uses it's own abi.

**Comment by dvc94ch** [comment]
Ah no the cabi stuff is ok as I thought. Rust's abi allows passing i128 integers through registers. The reason I thought that there was something wrong with the cabi code was this:

```
; core::mem::uninitialized
; Function Attrs: inlinehint
define internal <4 x i64> @_ZN4core3mem13uninitialized17h6085aee2759cd3d6E() unnamed_addr #1 {
start:
  %tmp_ret = alloca <4 x i64>
  %0 = load <4 x i64>, <4 x i64>* %tmp_ret
  br label %bb1

bb1:                                              ; preds = %start
  ret <4 x i64> %0
}
```

but I now think that this is a hack in rustc that is supposed to be optimized away before code generation and should be fixed by implementing insertBranch.

**Comment by dvc94ch** [comment]
So I implemented branch analysis (attached the patch for reference) but the above llvm-ir is still giving me trouble :/ any idea what's up there? I think this is a special case since it only happens once in libcore. I managed to build an old libcore.ll dump I created a couple of months back, so this seems to be the last issue.

```patch
From 352f1075ef943634adde7f88956e9650d9f0f853 Mon Sep 17 00:00:00 2001
From: David Craven <david@craven.ch>
Date: Tue, 15 Aug 2017 20:14:44 +0200
Subject: [PATCH] Add support for branch analysis.

---
 lib/Target/RISCV/RISCVInstrInfo.cpp  | 164 +++++++++++++++++++++++++++++++++++
 lib/Target/RISCV/RISCVInstrInfo.h    |  14 +++
 test/CodeGen/RISCV/analyze-branch.ll |  60 +++++++++++++
 3 files changed, 238 insertions(+)
 create mode 100644 test/CodeGen/RISCV/analyze-branch.ll

diff --git a/lib/Target/RISCV/RISCVInstrInfo.cpp b/lib/Target/RISCV/RISCVInstrInfo.cpp
index 8df08afa544..f204eecd215 100644
--- a/lib/Target/RISCV/RISCVInstrInfo.cpp
+++ b/lib/Target/RISCV/RISCVInstrInfo.cpp
@@ -79,3 +79,167 @@ void RISCVInstrInfo::loadRegFromStackSlot(MachineBasicBlock &MBB,
   else
     llvm_unreachable("Can't load this register from stack slot");
 }
+
+bool RISCVInstrInfo::analyzeBranch(MachineBasicBlock &MBB,
+                                   MachineBasicBlock *&TrueBlock,
+                                   MachineBasicBlock *&FalseBlock,
+                                   SmallVectorImpl<MachineOperand> &Condition,
+                                   bool AllowModify) const {
+  // Iterator to current instruction being considered.
+  MachineBasicBlock::iterator Instruction = MBB.end();
+
+  // Start from the bottom of the block and work up, examining the
+  // terminator instructions.
+  while (Instruction != MBB.begin()) {
+    --Instruction;
+
+    // Skip over debug values.
+    if (Instruction->isDebugValue())
+      continue;
+
+    // Working from the bottom, when we see a non-terminator
+    // instruction, we're done.
+    if (!Instruction->isTerminator())
+      break;
+
+    // Handle unconditional branches.
+    if (Instruction->isUnconditionalBranch()) {
+      if (!AllowModify) {
+        TrueBlock = Instruction->getOperand(1).getMBB();
+        continue;
+      }
+
+      // If the block has any instructions after a branch, delete them.
+      while (std::next(Instruction) != MBB.end()) {
+        std::next(Instruction)->eraseFromParent();
+      }
+
+      Condition.clear();
+      FalseBlock = nullptr;
+
+      // Delete the jump if it's equivalent to a fall-through.
+      if (MBB.isLayoutSuccessor(Instruction->getOperand(1).getMBB())) {
+        TrueBlock = nullptr;
+        Instruction->eraseFromParent();
+        Instruction = MBB.end();
+        continue;
+      }
+
+      // TrueBlock is used to indicate the unconditional destination.
+      TrueBlock = Instruction->getOperand(1).getMBB();
+      continue;
+    }
+
+    // Handle conditional branches.
+    if (Instruction->isConditionalBranch()) {
+      unsigned Opcode = Instruction->getOpcode();
+
+      // Multiple conditional branches are not handled here so only proceed if
+      // there are no conditions enqueued.
+      if (Condition.empty()) {
+        // TrueBlock is the target of the previously seen unconditional branch.
+        FalseBlock = TrueBlock;
+        TrueBlock = Instruction->getOperand(2).getMBB();
+        Condition.push_back(MachineOperand::CreateImm(Opcode));
+        Condition.push_back(Instruction->getOperand(0));
+        Condition.push_back(Instruction->getOperand(1));
+        continue;
+      }
+    }
+
+    return true;
+  }
+
+  // Return false indicating branch successfully analyzed.
+  return false;
+}
+
+
+unsigned RISCVInstrInfo::removeBranch(MachineBasicBlock &MBB,
+                                      int *BytesRemoved) const {
+  assert(!BytesRemoved && "code size not handled");
+
+  MachineBasicBlock::iterator Instruction = MBB.end();
+  unsigned Count = 0;
+
+  while (Instruction != MBB.begin()) {
+    --Instruction;
+    if (Instruction->isDebugValue())
+      continue;
+
+    if (!Instruction->isBranch())
+      break;
+
+    // Remove the branch.
+    Instruction->eraseFromParent();
+    Instruction = MBB.end();
+    ++Count;
+  }
+
+  return Count;
+}
+
+unsigned RISCVInstrInfo::insertBranch(MachineBasicBlock &MBB,
+                                      MachineBasicBlock *TrueBlock,
+                                      MachineBasicBlock *FalseBlock,
+                                      ArrayRef<MachineOperand> Condition,
+                                      const DebugLoc &DL,
+                                      int *BytesAdded) const {
+  // Shouldn't be a fall through.
+  assert(TrueBlock && "insertBranch must not be told to insert a fallthrough");
+  assert(!BytesAdded && "code size not handled");
+
+  // Unconditional branch.
+  if (Condition.empty()) {
+    BuildMI(&MBB, DL, get(RISCV::PseudoBR)).addMBB(TrueBlock);
+    return 1;
+  }
+
+  // Conditional branch.
+  BuildMI(&MBB, DL, get(Condition[0].getImm()))
+    .addReg(Condition[1].getReg())
+    .addReg(Condition[2].getReg())
+    .addMBB(TrueBlock);
+
+  if (FalseBlock) {
+    // Two way conditional branch. (if Condition then TrueBlock else FalseBlock)
+    BuildMI(&MBB, DL, get(RISCV::PseudoBR)).addMBB(FalseBlock);
+    return 2;
+  }
+
+  // One way Conditional branch. (if Condition then TrueBlock)
+  return 1;
+}
+
+bool RISCVInstrInfo::reverseBranchCondition(SmallVectorImpl<MachineOperand>
+                                            &Condition) const {
+  if (Condition.empty())
+    return true;
+
+  unsigned Opcode;
+  switch (Condition[0].getImm()) {
+  case RISCV::BEQ:
+    Opcode = RISCV::BNE;
+    break;
+  case RISCV::BNE:
+    Opcode = RISCV::BEQ;
+    break;
+  case RISCV::BLT:
+    Opcode = RISCV::BGE;
+    break;
+  case RISCV::BGE:
+    Opcode = RISCV::BLT;
+    break;
+  case RISCV::BLTU:
+    Opcode = RISCV::BGEU;
+    break;
+  case RISCV::BGEU:
+    Opcode = RISCV::BLTU;
+    break;
+  default:
+    return true;
+  }
+
+  Condition[0].setImm(Opcode);
+  return false;
+}
diff --git a/lib/Target/RISCV/RISCVInstrInfo.h b/lib/Target/RISCV/RISCVInstrInfo.h
index ea21efebb93..ffed350eadc 100644
--- a/lib/Target/RISCV/RISCVInstrInfo.h
+++ b/lib/Target/RISCV/RISCVInstrInfo.h
@@ -46,6 +46,20 @@ public:
                             MachineBasicBlock::iterator MBBI, unsigned DestReg,
                             int FrameIndex, const TargetRegisterClass *RC,
                             const TargetRegisterInfo *TRI) const override;
+
+  // Branch analysis.
+  bool analyzeBranch(MachineBasicBlock &MBB, MachineBasicBlock *&TBB,
+                     MachineBasicBlock *&FBB,
+                     SmallVectorImpl<MachineOperand> &Cond,
+                     bool AllowModify = false) const override;
+  unsigned insertBranch(MachineBasicBlock &MBB, MachineBasicBlock *TBB,
+                        MachineBasicBlock *FBB, ArrayRef<MachineOperand> Cond,
+                        const DebugLoc &DL,
+                        int *BytesAdded = nullptr) const override;
+  unsigned removeBranch(MachineBasicBlock &MBB,
+                        int *BytesRemoved = nullptr) const override;
+  bool
+  reverseBranchCondition(SmallVectorImpl<MachineOperand> &Cond) const override;
 };
 }
 
diff --git a/test/CodeGen/RISCV/analyze-branch.ll b/test/CodeGen/RISCV/analyze-branch.ll
new file mode 100644
index 00000000000..a1d87a86f29
--- /dev/null
+++ b/test/CodeGen/RISCV/analyze-branch.ll
@@ -0,0 +1,60 @@
+; RUN: llc -mtriple=riscv32 < %s | FileCheck %s
+
+; This test checks that LLVM can do basic stripping and reapplying of branches
+; to basic blocks.
+
+declare void @test_true()
+declare void @test_false()
+
+; !0 corresponds to a branch being taken, !1 to not being taken.
+!0 = !{!"branch_weights", i32 64, i32 4}
+!1 = !{!"branch_weights", i32 4, i32 64}
+
+define void @test_jal_fallthrough() nounwind {
+; CHECK-LABEL: test_jal_fallthrough:
+; CHECK: lui a0, %hi(test_true)
+; CHECK-NEXT: addi a0, a0, %lo(test_true)
+; CHECK-NEXT: jalr ra, a0
+  br label %jump
+jump:
+  call void @test_true()
+  ret void
+}
+
+define void @test_branch_fallthrough_taken(i32 %in) nounwind {
+; CHECK-LABEL: test_branch_fallthrough_taken:
+; CHECK: bne a0, zero, [[FALSE:.LBB[0-9]+_[0-9]+]]
+; CHECK: jal zero, [[TRUE:.LBB[0-9]+_[0-9]+]]
+; CHECK: [[TRUE]]:
+; CHECK: [[FALSE]]:
+  %bit = and i32 %in, 32768
+  %tst = icmp eq i32 %in, 0
+  br i1 %tst, label %true, label %false, !prof !0
+
+true:
+  call void @test_true()
+  ret void
+
+false:
+  call void @test_false()
+  ret void
+}
+
+define void @test_branch_fallthrough_nottaken(i32 %in) nounwind {
+; CHECK-LABEL: test_branch_fallthrough_nottaken:
+; CHECK: bne a0, zero, [[TRUE:.LBB[0-9]+_[0-9]+]]
+; CHECK: jal zero, [[FALSE:.LBB[0-9]+_[0-9]+]]
+; CHECK: [[TRUE]]:
+; CHECK: [[FALSE]]:
+  %bit = and i32 %in, 32768
+  %tst = icmp eq i32 %bit, 0
+  br i1 %tst, label %true, label %false, !prof !1
+
+true:
+  call void @test_true()
+  ret void
+
+false:
+  call void @test_false()
+  ret void
+}
\ No newline at end of file
-- 
2.11.1
```

**Comment by asb** [comment]
Hi David. Nothing immediately comes to mind, but I will circle back and try to help debug this. Today I'm trying to do what I can to move forwards the patches up for review, see also <http://lists.llvm.org/pipermail/llvm-dev/2017-August/116635.html>. Branch analysis is a high priority for me as obviously it's needed above O0, so I'll be spending more time on this next week if you haven't already found the answer since then.

I have done little testing for function prototypes that wouldn't be generated by a frontend that lowers to the RISC-V ABI, so it's very possible there are lurking issues there.

**Comment by dvc94ch** [comment]
Thank you for working on the llvm backend. Reading it is very educational and is a lot of fun :)
I'll close this PR for now since the discussion and the patches are out of date and will submit the branch analysis patch to the llvm mailing list once you've upstreamed the other patches (unless someone else submits a similar one first).
Sorry for being a little noisy, I don't know many people who get excited about blinking led's =P

**Comment by asb** [comment]
Being "noisy" is great! I appreciate having someone else kicking the tires and working on this. I'm looking forward to collaborating on getting more of your changes integrated. As you'll have seen in my message to the sw-dev group, I'm going to see if my attempts to rustle up code reviews for upstream LLVM are getting anywhere by the beginning of next week, then decide whether to collect changes downstream.

**Comment by asb** [comment]
Hi David. Given that the upstream code review bottleneck doesn't seem to be clearing up, I've gone ahead and created https://github.com/lowRISC/riscv-llvm-integration to allow productive downstream collaboration. The point is to integrate work prior to submitting upstream, and I'd really appreciate pull requests against that repo.

**Comment by dvc94ch** [comment]
Hi Alex. I'm currently focused on getting rust support for the hifive board to being useful. I'm planning on cleaning up the llvm patches afterwards, so it may be a couple of weeks before I get around to it.

**Pull request closed without merging**
